-- 0009_seed_exercises.sql
-- Seeds the canonical exercise library (spec §10).
--
-- GENERATED FILE. Do not edit by hand: run `node scripts/build-seed.mjs`
-- after changing data/exercises/catalog.json.
--
-- Idempotent by design. exercise_id is a stable slug, so re-running this after
-- importing an updated catalog updates the reference rows in place and leaves
-- every historical workout_sets reference intact (spec §48: never delete
-- historical observations).
--
-- nippard_tier is null on every row: the tier ratings are not sourced in this
-- repository and are not invented here. See lib/health/catalog.ts.

insert into exercises
  (exercise_id, name, primary_muscle_group, equipment, nippard_tier,
   muscle_subgroups, demonstration_url, active, apartment_gym)
values
  ('ab-wheel-rollout', 'Ab Wheel Rollout', 'Core', 'Bodyweight', null, array['Rectus Abdominis']::text[], null, true, true),
  ('barbell-back-squat', 'Barbell Back Squat', 'Quadriceps', 'Barbell', null, array['Vastus Lateralis', 'Glutes']::text[], null, true, false),
  ('barbell-deadlift', 'Barbell Deadlift', 'Hamstrings', 'Barbell', null, array['Biceps Femoris', 'Glutes', 'Erectors']::text[], null, true, false),
  ('barbell-row', 'Barbell Row', 'Back', 'Barbell', null, array['Mid Traps', 'Lats']::text[], null, true, false),
  ('bayesian-cable-curl', 'Bayesian Cable Curl', 'Biceps', 'Cable', null, array['Long Head Biceps']::text[], null, true, true),
  ('bench-dip', 'Bench Dip', 'Triceps', 'Bodyweight', null, array['Triceps']::text[], null, true, true),
  ('bulgarian-split-squat', 'Bulgarian Split Squat', 'Quadriceps', 'Dumbbell', null, array['Vastus Lateralis', 'Glutes']::text[], null, true, true),
  ('cable-chest-press', 'Cable Chest Press', 'Chest', 'Cable', null, array['Sternal Pectoralis', 'Triceps']::text[], null, true, true),
  ('cable-crunch', 'Cable Crunch', 'Core', 'Cable', null, array['Rectus Abdominis']::text[], null, true, true),
  ('cable-curl', 'Cable Curl', 'Biceps', 'Cable', null, array['Biceps Brachii']::text[], null, true, true),
  ('cable-face-pull', 'Cable Face Pull', 'Back', 'Cable', null, array['Rear Delts', 'Mid Traps']::text[], null, true, true),
  ('cable-flye', 'Cable Flye', 'Chest', 'Cable', null, array['Sternal Pectoralis']::text[], null, true, true),
  ('cable-hammer-curl', 'Cable Hammer Curl', 'Biceps', 'Cable', null, array['Brachialis', 'Brachioradialis']::text[], null, true, true),
  ('cable-hip-abduction', 'Cable Hip Abduction', 'Glutes', 'Cable', null, array['Gluteus Medius']::text[], null, true, true),
  ('cable-kickback', 'Cable Kickback', 'Glutes', 'Cable', null, array['Gluteus Maximus']::text[], null, true, true),
  ('cable-lateral-raise', 'Cable Lateral Raise', 'Shoulders', 'Cable', null, array['Side Delts']::text[], null, true, true),
  ('cable-pull-through', 'Cable Pull-Through', 'Hamstrings', 'Cable', null, array['Glutes', 'Biceps Femoris']::text[], null, true, true),
  ('cable-pullover', 'Cable Pullover', 'Back', 'Cable', null, array['Lats']::text[], null, true, true),
  ('cable-reverse-flye', 'Cable Reverse Flye', 'Shoulders', 'Cable', null, array['Rear Delts']::text[], null, true, true),
  ('cable-row', 'Cable Row', 'Back', 'Cable', null, array['Mid Traps', 'Rhomboids', 'Lats']::text[], null, true, true),
  ('cable-shrug', 'Cable Shrug', 'Back', 'Cable', null, array['Upper Traps']::text[], null, true, true),
  ('cable-triceps-pushdown', 'Cable Triceps Pushdown', 'Triceps', 'Cable', null, array['Lateral Head Triceps']::text[], null, true, true),
  ('cable-upright-row', 'Cable Upright Row', 'Shoulders', 'Cable', null, array['Side Delts', 'Upper Traps']::text[], null, true, true),
  ('cable-woodchop', 'Cable Woodchop', 'Core', 'Cable', null, array['Obliques']::text[], null, true, true),
  ('cable-wrist-curl', 'Cable Wrist Curl', 'Forearms', 'Cable', null, array['Wrist Flexors']::text[], null, true, true),
  ('chest-supported-dumbbell-row', 'Chest-Supported Dumbbell Row', 'Back', 'Dumbbell', null, array['Mid Traps', 'Rhomboids']::text[], null, true, true),
  ('chest-supported-row', 'Chest-Supported Row', 'Back', 'Machine', null, array['Mid Traps', 'Rhomboids']::text[], null, true, false),
  ('chin-up', 'Chin-Up', 'Back', 'Bodyweight', null, array['Lats', 'Biceps']::text[], null, true, true),
  ('close-grip-smith-machine-press', 'Close-Grip Smith Machine Press', 'Triceps', 'Smith Machine', null, array['Triceps', 'Sternal Pectoralis']::text[], null, true, true),
  ('concentration-curl', 'Concentration Curl', 'Biceps', 'Dumbbell', null, array['Biceps Brachii']::text[], null, true, true),
  ('cross-body-cable-extension', 'Cross-Body Cable Extension', 'Triceps', 'Cable', null, array['Long Head Triceps']::text[], null, true, true),
  ('dead-bug', 'Dead Bug', 'Core', 'Bodyweight', null, array['Transverse Abdominis']::text[], null, true, true),
  ('deficit-push-up', 'Deficit Push-Up', 'Chest', 'Bodyweight', null, array['Sternal Pectoralis']::text[], null, true, true),
  ('dip', 'Dip', 'Chest', 'Bodyweight', null, array['Costal Pectoralis', 'Triceps']::text[], null, true, true),
  ('dumbbell-bench-press', 'Dumbbell Bench Press', 'Chest', 'Dumbbell', null, array['Sternal Pectoralis', 'Triceps']::text[], null, true, true),
  ('dumbbell-curl', 'Dumbbell Curl', 'Biceps', 'Dumbbell', null, array['Biceps Brachii']::text[], null, true, true),
  ('dumbbell-flye', 'Dumbbell Flye', 'Chest', 'Dumbbell', null, array['Sternal Pectoralis']::text[], null, true, true),
  ('dumbbell-front-raise', 'Dumbbell Front Raise', 'Shoulders', 'Dumbbell', null, array['Front Delts']::text[], null, true, true),
  ('dumbbell-hip-thrust', 'Dumbbell Hip Thrust', 'Glutes', 'Dumbbell', null, array['Gluteus Maximus']::text[], null, true, true),
  ('dumbbell-incline-press', 'Dumbbell Incline Press', 'Chest', 'Dumbbell', null, array['Clavicular Pectoralis', 'Front Delts']::text[], null, true, true),
  ('dumbbell-kickback', 'Dumbbell Kickback', 'Triceps', 'Dumbbell', null, array['Lateral Head Triceps']::text[], null, true, true),
  ('dumbbell-lateral-raise', 'Dumbbell Lateral Raise', 'Shoulders', 'Dumbbell', null, array['Side Delts']::text[], null, true, true),
  ('dumbbell-lunge', 'Dumbbell Lunge', 'Quadriceps', 'Dumbbell', null, array['Vastus Lateralis', 'Glutes']::text[], null, true, true),
  ('dumbbell-overhead-extension', 'Dumbbell Overhead Extension', 'Triceps', 'Dumbbell', null, array['Long Head Triceps']::text[], null, true, true),
  ('dumbbell-overhead-press', 'Dumbbell Overhead Press', 'Shoulders', 'Dumbbell', null, array['Front Delts', 'Triceps']::text[], null, true, true),
  ('dumbbell-reverse-flye', 'Dumbbell Reverse Flye', 'Shoulders', 'Dumbbell', null, array['Rear Delts']::text[], null, true, true),
  ('dumbbell-reverse-wrist-curl', 'Dumbbell Reverse Wrist Curl', 'Forearms', 'Dumbbell', null, array['Wrist Extensors']::text[], null, true, true),
  ('dumbbell-shrug', 'Dumbbell Shrug', 'Back', 'Dumbbell', null, array['Upper Traps']::text[], null, true, true),
  ('dumbbell-side-bend', 'Dumbbell Side Bend', 'Core', 'Dumbbell', null, array['Obliques']::text[], null, true, true),
  ('dumbbell-skull-crusher', 'Dumbbell Skull Crusher', 'Triceps', 'Dumbbell', null, array['Long Head Triceps']::text[], null, true, true),
  ('dumbbell-wrist-curl', 'Dumbbell Wrist Curl', 'Forearms', 'Dumbbell', null, array['Wrist Flexors']::text[], null, true, true),
  ('farmers-carry', 'Farmer’s Carry', 'Forearms', 'Dumbbell', null, array['Grip', 'Upper Traps']::text[], null, true, true),
  ('glute-bridge', 'Glute Bridge', 'Glutes', 'Bodyweight', null, array['Gluteus Maximus']::text[], null, true, true),
  ('goblet-squat', 'Goblet Squat', 'Quadriceps', 'Dumbbell', null, array['Vastus Lateralis', 'Glutes']::text[], null, true, true),
  ('hack-squat', 'Hack Squat', 'Quadriceps', 'Machine', null, array['Vastus Lateralis', 'Rectus Femoris']::text[], null, true, false),
  ('hammer-curl', 'Hammer Curl', 'Biceps', 'Dumbbell', null, array['Brachialis', 'Brachioradialis']::text[], null, true, true),
  ('hanging-knee-raise', 'Hanging Knee Raise', 'Core', 'Bodyweight', null, array['Lower Rectus Abdominis']::text[], null, true, true),
  ('hanging-leg-raise', 'Hanging Leg Raise', 'Core', 'Bodyweight', null, array['Lower Rectus Abdominis', 'Hip Flexors']::text[], null, true, true),
  ('high-to-low-cable-flye', 'High-to-Low Cable Flye', 'Chest', 'Cable', null, array['Costal Pectoralis']::text[], null, true, true),
  ('hip-thrust', 'Hip Thrust', 'Glutes', 'Barbell', null, array['Gluteus Maximus']::text[], null, true, false),
  ('incline-dumbbell-curl', 'Incline Dumbbell Curl', 'Biceps', 'Dumbbell', null, array['Long Head Biceps']::text[], null, true, true),
  ('incline-dumbbell-flye', 'Incline Dumbbell Flye', 'Chest', 'Dumbbell', null, array['Clavicular Pectoralis']::text[], null, true, true),
  ('inverted-row', 'Inverted Row', 'Back', 'Bodyweight', null, array['Mid Traps', 'Rhomboids']::text[], null, true, true),
  ('lat-pulldown', 'Lat Pulldown', 'Back', 'Cable', null, array['Lats', 'Biceps']::text[], null, true, true),
  ('leaning-cable-lateral-raise', 'Leaning Cable Lateral Raise', 'Shoulders', 'Cable', null, array['Side Delts']::text[], null, true, true),
  ('leg-extension', 'Leg Extension', 'Quadriceps', 'Machine', null, array['Rectus Femoris', 'Vastus Medialis']::text[], null, true, false),
  ('leg-press', 'Leg Press', 'Quadriceps', 'Machine', null, array['Vastus Lateralis', 'Glutes']::text[], null, true, false),
  ('low-to-high-cable-flye', 'Low-to-High Cable Flye', 'Chest', 'Cable', null, array['Clavicular Pectoralis']::text[], null, true, true),
  ('lying-leg-curl', 'Lying Leg Curl', 'Hamstrings', 'Machine', null, array['Biceps Femoris']::text[], null, true, false),
  ('machine-chest-press', 'Machine Chest Press', 'Chest', 'Machine', null, array['Sternal Pectoralis', 'Triceps']::text[], null, true, false),
  ('machine-crunch', 'Machine Crunch', 'Core', 'Machine', null, array['Rectus Abdominis']::text[], null, true, false),
  ('machine-lateral-raise', 'Machine Lateral Raise', 'Shoulders', 'Machine', null, array['Side Delts']::text[], null, true, false),
  ('neutral-grip-pull-up', 'Neutral-Grip Pull-Up', 'Back', 'Bodyweight', null, array['Lats', 'Biceps']::text[], null, true, true),
  ('neutral-grip-pulldown', 'Neutral-Grip Pulldown', 'Back', 'Cable', null, array['Lats', 'Biceps']::text[], null, true, true),
  ('nordic-curl', 'Nordic Curl', 'Hamstrings', 'Bodyweight', null, array['Biceps Femoris']::text[], null, true, true),
  ('overhead-cable-triceps-extension', 'Overhead Cable Triceps Extension', 'Triceps', 'Cable', null, array['Long Head Triceps']::text[], null, true, true),
  ('pallof-press', 'Pallof Press', 'Core', 'Cable', null, array['Obliques', 'Transverse Abdominis']::text[], null, true, true),
  ('pec-deck', 'Pec Deck', 'Chest', 'Machine', null, array['Sternal Pectoralis']::text[], null, true, false),
  ('plank', 'Plank', 'Core', 'Bodyweight', null, array['Rectus Abdominis', 'Transverse Abdominis']::text[], null, true, true),
  ('preacher-curl', 'Preacher Curl', 'Biceps', 'Dumbbell', null, array['Short Head Biceps']::text[], null, true, true),
  ('pull-up', 'Pull-Up', 'Back', 'Bodyweight', null, array['Lats', 'Biceps']::text[], null, true, true),
  ('push-up', 'Push-Up', 'Chest', 'Bodyweight', null, array['Sternal Pectoralis', 'Triceps']::text[], null, true, true),
  ('reverse-curl', 'Reverse Curl', 'Biceps', 'Cable', null, array['Brachioradialis']::text[], null, true, true),
  ('reverse-lunge', 'Reverse Lunge', 'Quadriceps', 'Dumbbell', null, array['Glutes', 'Vastus Lateralis']::text[], null, true, true),
  ('reverse-pec-deck', 'Reverse Pec Deck', 'Shoulders', 'Machine', null, array['Rear Delts']::text[], null, true, false),
  ('romanian-deadlift', 'Romanian Deadlift', 'Hamstrings', 'Dumbbell', null, array['Biceps Femoris', 'Glutes']::text[], null, true, true),
  ('rope-triceps-pushdown', 'Rope Triceps Pushdown', 'Triceps', 'Cable', null, array['Lateral Head Triceps']::text[], null, true, true),
  ('rowing-machine', 'Rowing Machine', 'Cardio', 'Machine', null, array['Cardiovascular', 'Mid Traps']::text[], null, true, false),
  ('seal-row', 'Seal Row', 'Back', 'Barbell', null, array['Mid Traps', 'Rhomboids']::text[], null, true, false),
  ('seated-calf-raise', 'Seated Calf Raise', 'Calves', 'Machine', null, array['Soleus']::text[], null, true, false),
  ('seated-dumbbell-press', 'Seated Dumbbell Press', 'Shoulders', 'Dumbbell', null, array['Front Delts', 'Triceps']::text[], null, true, true),
  ('seated-leg-curl', 'Seated Leg Curl', 'Hamstrings', 'Machine', null, array['Biceps Femoris', 'Semitendinosus']::text[], null, true, false),
  ('single-arm-dumbbell-row', 'Single-Arm Dumbbell Row', 'Back', 'Dumbbell', null, array['Lats', 'Mid Traps']::text[], null, true, true),
  ('single-leg-calf-raise', 'Single-Leg Calf Raise', 'Calves', 'Bodyweight', null, array['Gastrocnemius']::text[], null, true, true),
  ('single-leg-romanian-deadlift', 'Single-Leg Romanian Deadlift', 'Hamstrings', 'Dumbbell', null, array['Biceps Femoris', 'Glutes']::text[], null, true, true),
  ('sissy-squat', 'Sissy Squat', 'Quadriceps', 'Bodyweight', null, array['Rectus Femoris']::text[], null, true, true),
  ('smith-machine-bench-press', 'Smith Machine Bench Press', 'Chest', 'Smith Machine', null, array['Sternal Pectoralis', 'Triceps']::text[], null, true, true),
  ('smith-machine-bulgarian-split-squat', 'Smith Machine Bulgarian Split Squat', 'Quadriceps', 'Smith Machine', null, array['Vastus Lateralis', 'Glutes']::text[], null, true, true),
  ('smith-machine-calf-raise', 'Smith Machine Calf Raise', 'Calves', 'Smith Machine', null, array['Gastrocnemius']::text[], null, true, true),
  ('smith-machine-front-squat', 'Smith Machine Front Squat', 'Quadriceps', 'Smith Machine', null, array['Rectus Femoris', 'Vastus Medialis']::text[], null, true, true),
  ('smith-machine-hip-thrust', 'Smith Machine Hip Thrust', 'Glutes', 'Smith Machine', null, array['Gluteus Maximus']::text[], null, true, true),
  ('smith-machine-incline-press', 'Smith Machine Incline Press', 'Chest', 'Smith Machine', null, array['Clavicular Pectoralis', 'Front Delts']::text[], null, true, true),
  ('smith-machine-overhead-press', 'Smith Machine Overhead Press', 'Shoulders', 'Smith Machine', null, array['Front Delts', 'Triceps']::text[], null, true, true),
  ('smith-machine-romanian-deadlift', 'Smith Machine Romanian Deadlift', 'Hamstrings', 'Smith Machine', null, array['Biceps Femoris', 'Glutes']::text[], null, true, true),
  ('smith-machine-row', 'Smith Machine Row', 'Back', 'Smith Machine', null, array['Mid Traps', 'Lats']::text[], null, true, true),
  ('smith-machine-shrug', 'Smith Machine Shrug', 'Back', 'Smith Machine', null, array['Upper Traps']::text[], null, true, true),
  ('smith-machine-squat', 'Smith Machine Squat', 'Quadriceps', 'Smith Machine', null, array['Vastus Lateralis', 'Glutes']::text[], null, true, true),
  ('spider-curl', 'Spider Curl', 'Biceps', 'Dumbbell', null, array['Short Head Biceps']::text[], null, true, true),
  ('stair-climber', 'Stair Climber', 'Cardio', 'Machine', null, array['Cardiovascular', 'Glutes']::text[], null, true, false),
  ('standing-dumbbell-calf-raise', 'Standing Dumbbell Calf Raise', 'Calves', 'Dumbbell', null, array['Gastrocnemius']::text[], null, true, true),
  ('stationary-bike', 'Stationary Bike', 'Cardio', 'Machine', null, array['Cardiovascular']::text[], null, true, false),
  ('step-up', 'Step-Up', 'Quadriceps', 'Dumbbell', null, array['Vastus Lateralis', 'Glutes']::text[], null, true, true),
  ('straight-arm-pulldown', 'Straight-Arm Pulldown', 'Back', 'Cable', null, array['Lats']::text[], null, true, true),
  ('treadmill-incline-walk', 'Treadmill Incline Walk', 'Cardio', 'Treadmill', null, array['Cardiovascular']::text[], null, true, true),
  ('treadmill-run', 'Treadmill Run', 'Cardio', 'Treadmill', null, array['Cardiovascular']::text[], null, true, true),
  ('treadmill-walk', 'Treadmill Walk', 'Cardio', 'Treadmill', null, array['Cardiovascular']::text[], null, true, true),
  ('walking-lunge', 'Walking Lunge', 'Quadriceps', 'Dumbbell', null, array['Vastus Lateralis', 'Glutes']::text[], null, true, true),
  ('wide-grip-pulldown', 'Wide-Grip Pulldown', 'Back', 'Cable', null, array['Lats', 'Teres Major']::text[], null, true, true)
on conflict (exercise_id) do update set
  name = excluded.name,
  primary_muscle_group = excluded.primary_muscle_group,
  equipment = excluded.equipment,
  nippard_tier = excluded.nippard_tier,
  muscle_subgroups = excluded.muscle_subgroups,
  demonstration_url = excluded.demonstration_url,
  active = excluded.active,
  apartment_gym = excluded.apartment_gym,
  updated_at = now();
